services:
  web:
    build: .
    container_name: users_api_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=users_api
      - DB_USER=root
      - DB_PASS=rootpassword
    networks:
      - users_api_network

  db:
    image: mysql:8.0
    container_name: users_api_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users_api
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - users_api_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: users_api_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - users_api_network

volumes:
  db_data:

networks:
  users_api_network:
    driver: bridge